proxy-providers:
  sublink:
    url: "__SUBSCRIBE_URL__"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    exclude-filter: ".*(åˆ°æœŸ|è¿‡æœŸ|é‡ç½®|å‰©ä½™|æµé‡|å…¬ç›Š|å…è´¹|é‚®ç®±|ç½‘ç«™|å®˜ç½‘|é¢‘é“|å¯¼èˆª|åœ°å€|è®¢é˜…).*"

proxies:
  - {name: ğŸ¯ Direct, type: direct}
